### ISSUE TITLE
Project should include Cargo.lock

### ISSUE THREAD

**Issue by 2xsaiko** [ArniDagur/python-adblock#15]
The repo should include the Cargo.lock file so that dependency versions don't change between different clones of the same commit. Right now 0.3.2 of this tries to build using adblock 0.3.4 (to specify an absolute package version, use `adblock = "=0.3.2"`, this is the workaround I'm using to build right now since otherwise it fails with a compile error)

**Comment by ArniDagur** [comment]
Thanks for pointing this out! I've submitted a PR that adds the `Cargo.lock` file to git, as is the best practice when writing a library. For some reason I thought `0.3.2` meant `=0.3.2` instead of `^0.3.2`.

**Comment by 2xsaiko** [comment]
Thanks! That helps a lot with [packaging][1] since now I don't have to ship my own Cargo.lock!

[1]: https://git.sr.ht/~dblsaiko/ebuilds/tree/master/dev-python/adblock
