### ISSUE TITLE
Windows 32bit wheels?

### ISSUE THREAD

**Issue by The-Compiler** [ArniDagur/python-adblock#25]
I noticed that there currently only are 64-bit wheels for Windows, which doesn't let me package a 32-bit release of qutebrowser for Windows anymore (or at least not if I want to include the adblock dependency).

I'm not sure if I should drop it actually... it's still being downloaded by some people. According to https://utilify.me/github-release-stats with https://github.com/qutebrowser/qutebrowser:

Downloads | Filename | Size
-- | -- | --
144 | qutebrowser-1.14.1-windows-standalone-win32.zip | 97 MB
214 | qutebrowser-1.14.1-win32.exe | 71 MB
798 | qutebrowser-1.14.1-windows-standalone-amd64.zip | 115 MB
1 423 | qutebrowser-1.14.1-amd64.exe | 82 MB
| |
249 | qutebrowser-1.14.0-windows-standalone-win32.zip | 96 MB
265 | qutebrowser-1.14.0-win32.exe | 70 MB
890 | qutebrowser-1.14.0-windows-standalone-amd64.zip | 114 MB
1 459 | qutebrowser-1.14.0-amd64.exe | 80 MB
| |
235 | qutebrowser-1.13.1-windows-standalone-win32.zip | 102 MB
326 | qutebrowser-1.13.1-win32.exe | 75 MB
1 368 | qutebrowser-1.13.1-windows-standalone-amd64.zip | 119 MB
2 242 | qutebrowser-1.13.1-amd64.exe | 86 MB

I'm okay with dropping it entirely if you prefer not dealing with it, but I think it shouldn't be much effort to add it to the CI? According to https://github.com/actions/setup-python you can do `architecture: x86` with `setup-python` and then I'd hope maturin would just pick that up?

**Comment by ArniDagur** [comment]
> According to https://github.com/actions/setup-python you can do architecture: x86 with setup-python and then I'd hope maturin would just pick that up?

If it's as simple as that, I don't see a problem with it. I simply hadn't considered the possibility that anyone still used 32-bit non-embedded systems.

**Comment by The-Compiler** [comment]
Yay, nice, thank you! Any plans for a new release with this in soon? I plan to release qutebrowser v2.0.0 very soon (likely today) and it'd be nice if I could still push 32bit Windows releases with adblocking.

If not, that's okay as well, then I'll probably reintroduce 32-bit releases with v2.0.1 or so.

**Comment by ArniDagur** [comment]
I can make a release today.

**Comment by The-Compiler** [comment]
You might've noticed already, but if not: It looks like publishing the wheels to PyPI [failed](https://github.com/ArniDagur/python-adblock/runs/1780395058?check_suite_focus=true#step:13:53) - I think the [maturand publish](https://github.com/ArniDagur/python-adblock/blob/master/.github/workflows/ci.yml#L171) step might need the `--target ${{ env.ACTIONS_RUST_TARGET }}` flag as well? (Though I'm a bit surprised it doesn't just upload the already built wheels)

**Comment by ArniDagur** [comment]
For now I've uploaded the `win32` wheels manually. I'll have to fix the CI before the next release.
