### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by The-Compiler** [ArniDagur/python-adblock#28]
While you're working on https://github.com/ArniDagur/python-adblock/pull/26 already, it might be good to update the supported Python versions?

- Python 3.5 is [end of life](https://devguide.python.org/#status-of-python-branches) and dropped from qutebrowser master, so I suppose it can be removed here as well.
- It'd be nice to support the Python 3.10 Alpha already, maybe? I'd like to add it to the CI for qutebrowser soon-ish, and this is one of the blockers (though there seem to be others). Looks like GitHub Actions understands `3.10-dev` as Python version.

**Comment by ArniDagur** [comment]
I have already dropped 3.5 support. I can add the 3.10 alpha.

**Comment by The-Compiler** [comment]
Ah, I missed that, I only looked at the last PyPI release. Adding 3.10 would be great! I'll just skip installing `adblock` for Python 3.10 for now, so no hurry.

**Comment by ArniDagur** [comment]
@The-Compiler Python 3.10 should be supported now.

**Comment by The-Compiler** [comment]
Seems to work fine - no worries and thanks!
