### ISSUE TITLE
Drop poetry

### ISSUE THREAD

**Issue by ahesford** [ArniDagur/python-adblock#33]
Please drop the `poetry` build dependency. This tool is a poorly conceived mashup of packaging, installation and virtual environment management that doesn't fit well with distribution-level packaging. Setuptools compatibility would be ideal, since you are relying on bridges to other languages that don't (yet) play nicely with PEP517/PEP518 build systems.

Edit: I am not familiar with maturin, but it seems that it provides PEP 517 compliance and is responsible for producing an installable wheel on the local system. Perhaps updating `pyproject.toml` to use maturin directly is sufficient, but there remains no reason to drag poetry into this workflow.

**Comment by ArniDagur** [comment]
Yeah, I agree. Updating `pyproject.toml` to use Maturin directly will allow for sdists (see https://github.com/ArniDagur/python-adblock/issues/30) and PEP 517 compliance. I will do that.

**Comment by ArniDagur** [comment]
See https://github.com/ArniDagur/python-adblock/commit/dc33223fcb1583bf31b89474ec299d45d8f80ef0

**Comment by ahesford** [comment]
Thanks, looks good.
