### ISSUE TITLE
tests fail: No constructor defined on OpenBSD

### ISSUE THREAD

**Issue by dkarama** [ArniDagur/python-adblock#36]
I'm trying to port py-adblock to OpenBSD, so far the build is successful but there are still
some test and runtime failures. 
The system is OpenBSD-current amd64.
py-adblock-0.4.2 built with maturin-0.9.0, py-dephel-0.8.3 and  python-3.8.8.
I've attached the test log below.
[test.log](https://github.com/ArniDagur/python-adblock/files/6136196/test.log)

**Comment by ArniDagur** [comment]
Are you sure this is not a PyO3 issue? Are you using https://github.com/PyO3/maturin/pull/469 for PyO3?

**Comment by dkarama** [comment]
The changes mentioned in that pull I've had already dealt with, the build is successful though there is something which goes wrong in the tests particularly with pyo3. Are the pyo3 crates really required while building, I ask since they are not mentioned in the Cargo.toml of maturin.
Is [PyO3/pyo3](https://github.com/PyO3/pyo3) package required while building?

**Comment by ArniDagur** [comment]
> Is PyO3/pyo3 package required while building?

Yes. PyO3 is an important dependency for `python-adblock`, since it is what allows us to create Rust bindings for Python.

**Comment by frakswe** [comment]
@dkarama 

How are things coming along? i tried myself but i'm too oldschool and reluctant to learn these modern languages, will you document how you built it for OpenBSD ?

**Comment by dkarama** [comment]
@frakswe 

Both py-adblock and maturin ports are ready with me. The error will persist until https://github.com/PyO3/maturin/pull/496 is pulled in. Checkout [jasperla/openbsd-wip](https://github.com/jasperla/openbsd-wip) in the meanwhile, I will post these ports by today.

**Comment by messense** [comment]
I think the error is coming from https://github.com/PyO3/pyo3/blob/7ac75366c27d5be6cc8fd5b344da1953c12d2c3e/src/pyclass.rs#L112 , @davidhewitt do you by any chance know what's going on?

**Comment by davidhewitt** [comment]
👍 My guess is that the `inventory` dependency might be the cause, which is required on PyO3 0.13. `inventory` relies on platform-specific knowledge so I wouldn't be suprised if it's not implemented fully for OpenBSD.

On PyO3 `main` (to be released in 0.14) `inventory` is opt-in, so I guess it's not used when you tested against upstream PyO3 which is why it looks like it's fixed.

**Comment by dkarama** [comment]
@ArniDagur : Using the latest git HEAD of `pyo3` produces a functional package. I've tested with `qutebrowser`. All tests pass. I'll just have to wait for you to update to the lastest `pyo3` as and when it is released. Hopefully `pyo3` with `inventory` is not required by your build, it works fine without.

**Comment by messense** [comment]
> 👍 My guess is that the `inventory` dependency might be the cause, which is required on PyO3 0.13. `inventory` relies on platform-specific knowledge so I wouldn't be suprised if it's not implemented fully for OpenBSD.
> 
> On PyO3 `main` (to be released in 0.14) `inventory` is opt-in, so I guess it's not used when you tested against upstream PyO3 which is why it looks like it's fixed.

[`ctor`](https://github.com/mmastrac/rust-ctor) which `inventory` is based on claims support for OpenBSD, but I guess it may not be tested on OpenBSD.

**Comment by messense** [comment]
Ahh, OpenBSD support is added in `ctor` `0.1.19`, but `python-adblock` locks it to `0.1.16`: https://github.com/ArniDagur/python-adblock/blob/6c0619b2f5221567b614cf650ef37e4546eee1a1/Cargo.lock#L99-L107

**Comment by dkarama** [comment]
Also @messense, how do I force any single python version if multiple versions are avaialble. The build system produces a wheel for very available python version. See https://github.com/jasperla/openbsd-wip/issues/142.

**Comment by messense** [comment]
> Also @messense, how do I force any single python version if multiple versions are avaialble. The build system produces a wheel for very available python version. See [jasperla/openbsd-wip#142](https://github.com/jasperla/openbsd-wip/issues/142).

You can use `maturin build -i pythonXY` to specify a python interpreter.

**Comment by ArniDagur** [comment]
> Ahh, OpenBSD support is added in ctor 0.1.19, but python-adblock locks it to 0.1.16:

Dependencies have been updated.

**Comment by dkarama** [comment]
Thanks, works fine now.
