### ISSUE TITLE
Expose the different Rust errors as Python exceptions

### ISSUE THREAD

**Issue by ArniDagur** [ArniDagur/python-adblock#44]
Currently, users have to parse the error string, which is not ideal. See https://github.com/qutebrowser/qutebrowser/commit/7da7110bc73170647d4c48520f639e3fd2e2e802
```python
try:
  self._engine.deserialize_from_file(str(self._cache_path))
except ValueError as e:
  if str(e) != "DeserializationError":
      # All Rust exceptions get turned into a ValueError by
      # python-adblock
      raise
  message.error("Reading adblock filter data failed (corrupted data?). "
                "Please run :adblock-update.")
```

**Comment by The-Compiler** [comment]
Thanks! Handling this in an unified way [is a bit of a pain](https://github.com/qutebrowser/qutebrowser/commit/6dd402c0d0f7665d32a74c43c5b4cf5dc8aff28d) for qutebrowser now, but it was the right thing to do and I suppose at some point we can drop support for < 0.5.0.
