### ISSUE TITLE
Release new version with updated adblock-rust

### ISSUE THREAD

**Issue by edio** [ArniDagur/python-adblock#45]
First of all, let me thank you for the great work you've done here, and how tremendously you've helped qutebrowser users.

I'd like to request an update of this library, because some ads are not blocked anymore, and I suspect an outdated adblock-rust may be the cause.

Explaining how to build this https://github.com/ArniDagur/python-adblock/issues/32 would also be of great help.

**Comment by ArniDagur** [comment]
Does the `README.md` suffice as it is now?

**Comment by edio** [comment]
@ArniDagur , I can only guess, you intended to respond to #32 

With regards to this issue, I see new version in the repo, and I think this issue can be closed.
Thanks a lot for your work!
