### ISSUE TITLE
Failing test suite on python 3.10.0

### ISSUE THREAD

**Issue by Foxboron** [ArniDagur/python-adblock#55]
<pre>
py3.9 >>> "3.9" >= "3.6"
True
py3.9 >>> "3.9.0" >= "3.6"
True
py3.9 >>> "3.10.0" >= "3.6"
False
</pre>

I'm speechless at this being an actual problem.

https://rebuilds.foutrelis.com/log/python-adblock.log

**Comment by ArniDagur** [comment]
Should be fixed in new release.

**Comment by Foxboron** [comment]
Thanks!
